all:
  hosts:
    laprimaire_2022:
      ansible_host: "{{ (base_hostname == 'laprimaire.org.test') | ternary('2022.' + base_hostname, '51.159.163.166') }}"
      ansible_ssh_private_key_file: "{{ (base_hostname == 'laprimaire.org.test') | ternary('/vagrant/.vagrant/machines/laprimaire_2022/virtualbox/private_key', '/vagrant/key/laprimaire.org') }}"
      ansible_ssh_user: root
      ansible_become: yes
    org:
      ansible_host: "org.{{ base_hostname }}"
    blog:
      ansible_host: "2022.{{ base_hostname }}"
    monitoring:
      ansible_host: "monitoring.infra.{{ base_hostname }}"
    metrics:
      ansible_host: "metrics.infra.{{ base_hostname }}"
    logs:
      ansible_host: "logs.infra.{{ base_hostname }}"
    analytics:
      ansible_host: "analytics.infra.{{ base_hostname }}"

infra:
  hosts:
    monitoring:
    metrics:
    logs:
    analytics:
      vouch_public_locations:
        # Allow Vouch to bypass authentication for
        # the routes used to perform analytics.
        - "~ /matomo\\.(js|php)"

server:
  hosts:
    laprimaire_2022:
