name: Ansible Lint

on: [push, pull_request]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint Ansible Playbook
      uses: iranzo/ansible-lint-action@v4.1.1
      with:
        # FIXME
        # Globbing is broken at the moment:
        # https://github.com/ansible/ansible-lint-action/issues/30
        #targets: "**/*.{yaml,yml}"
        targets: |
          provisioning/requirements.yml
          provisioning/playbook.yml
          provisioning/roles/laprimaire.monitoring/tasks/grafana.yml
          provisioning/roles/laprimaire.monitoring/tasks/main.yml
          provisioning/roles/laprimaire.monitoring/tasks/prometheus.yml
          provisioning/roles/laprimaire.monitoring/defaults/main/grafana.yml
          provisioning/roles/laprimaire.monitoring/defaults/main/main.yml
          provisioning/roles/laprimaire.monitoring/defaults/main/prometheus.yml
          provisioning/roles/laprimaire.monitoring/handlers/main.yml
          provisioning/roles/laprimaire.reverse-proxy/tasks/main.yml
          provisioning/roles/laprimaire.reverse-proxy/defaults/main.yml
          provisioning/roles/laprimaire.reverse-proxy/handlers/main.yml
          provisioning/roles/laprimaire.logs/tasks/main.yml
          provisioning/roles/laprimaire.logs/defaults/main.yml
          provisioning/roles/laprimaire.logs/handlers/main.yml
          provisioning/roles/laprimaire.analytics/tasks/main.yml
          provisioning/roles/laprimaire.analytics/defaults/main.yml
          provisioning/roles/laprimaire.ssl-certs/tasks/main.yml
          provisioning/roles/laprimaire.blog/files/content/themes/lyra/routes.yaml
          provisioning/roles/laprimaire.blog/tasks/main.yml
          provisioning/roles/laprimaire.blog/defaults/main.yml
          provisioning/roles/laprimaire.blog/handlers/main.yml
          provisioning/roles/laprimaire.forum/tasks/main.yml
          provisioning/roles/laprimaire.forum/defaults/main.yml
          provisioning/inventories/development/hosts_var/laprimaire_2022/main.yml
          provisioning/inventories/development/hosts.yml
          provisioning/inventories/production/hosts_var/laprimaire_2022/main.yml
          provisioning/inventories/production/hosts_var/laprimaire_2022/vault_main.yml
          provisioning/inventories/production/hosts.yml
          provisioning/group_vars/all/main.yml
        override-deps: |
          ansible==2.9
          ansible-lint==4.3.7
        args: ""
